# vim:sw=2:et:

language: erlang
sudo: false
matrix:
    include:
      - otp_release: 21.3
      - otp_release: 20.3
      - otp_release: 19.3
      - otp_release: 18.3
        dist: trusty
      - otp_release: 17.5
        dist: trusty
      - otp_release: R16B03-1
        dist: trusty

install:
  - curl -O -L https://s3.amazonaws.com/rebar3/rebar3
  - chmod +x rebar3

script:
  - ./rebar3 do compile,eunit,dialyzer

after_success:
  - ./rebar3 coveralls send

notifications:
  email:
    recipients:
      - jean-sebastien.pedron@dumbbell.fr
    on_success: change
    on_failure: always

cache:
  directories:
    - $HOME/.cache/rebar3/hex/default
    - $HOME/_build/default/rebar3_${TRAVIS_OTP_RELEASE}_plt
