# vim:sw=2:et:

language: erlang
otp_release:
  - '19.3'
  - '18.3'
  - '17.5'
  - 'R16B03-1'

install:
  - curl -O -L https://s3.amazonaws.com/rebar3/rebar3
  - chmod +x rebar3
  - ./rebar3 update

script:
  - ./rebar3 compile
  - ./rebar3 eunit skip_deps=true
  - ./rebar3 dialyzer

after_success:
  - ./rebar3 coveralls send

notifications:
  email:
    recipients:
      - jean-sebastien.pedron@dumbbell.fr
    on_success: change
    on_failure: always
